package com.pallol.novela.entities;
// Generated 25/07/2019 01:09:25 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Capitulo generated by hbm2java
 */
@Entity
@Table(name="capitulo"
    ,catalog="noveladb"
)
public class Capitulo  implements java.io.Serializable {


     private Integer capituloId;
     private Novela novela;
     private String nombre;
     private String orden;

    public Capitulo() {
    }

	
    public Capitulo(Novela novela) {
        this.novela = novela;
    }
    public Capitulo(Novela novela, String nombre, String orden) {
       this.novela = novela;
       this.nombre = nombre;
       this.orden = orden;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="capitulo_id", unique=true, nullable=false)
    public Integer getCapituloId() {
        return this.capituloId;
    }
    
    public void setCapituloId(Integer capituloId) {
        this.capituloId = capituloId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="novela_id_fk", nullable=false)
    public Novela getNovela() {
        return this.novela;
    }
    
    public void setNovela(Novela novela) {
        this.novela = novela;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="orden", length=45)
    public String getOrden() {
        return this.orden;
    }
    
    public void setOrden(String orden) {
        this.orden = orden;
    }




}


