package com.pallol.novela.entities;
// Generated 25/07/2019 01:09:25 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name="comentario"
    ,catalog="noveladb"
)
public class Comentario  implements java.io.Serializable {


     private Integer comentarioId;
     private Novela novela;
     private Usuario usuario;
     private String texto;

    public Comentario() {
    }

	
    public Comentario(Novela novela, Usuario usuario) {
        this.novela = novela;
        this.usuario = usuario;
    }
    public Comentario(Novela novela, Usuario usuario, String texto) {
       this.novela = novela;
       this.usuario = usuario;
       this.texto = texto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="comentario_id", unique=true, nullable=false)
    public Integer getComentarioId() {
        return this.comentarioId;
    }
    
    public void setComentarioId(Integer comentarioId) {
        this.comentarioId = comentarioId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="novela_id_fk", nullable=false)
    public Novela getNovela() {
        return this.novela;
    }
    
    public void setNovela(Novela novela) {
        this.novela = novela;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id_fk", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="texto", length=65535)
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }




}


