package com.pallol.novela.entities;
// Generated 25/07/2019 01:09:25 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Galeria generated by hbm2java
 */
@Entity
@Table(name="galeria"
    ,catalog="noveladb"
)
public class Galeria  implements java.io.Serializable {


     private Integer galeriaId;
     private Novela novela;
     private String url;

    public Galeria() {
    }

    public Galeria(Novela novela, String url) {
       this.novela = novela;
       this.url = url;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="galeria_id", unique=true, nullable=false)
    public Integer getGaleriaId() {
        return this.galeriaId;
    }
    
    public void setGaleriaId(Integer galeriaId) {
        this.galeriaId = galeriaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="novela_id_fk", nullable=false)
    public Novela getNovela() {
        return this.novela;
    }
    
    public void setNovela(Novela novela) {
        this.novela = novela;
    }

    
    @Column(name="url", nullable=false, length=65535)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


