package com.pallol.novela.entities;
// Generated 25/07/2019 01:09:25 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="menu"
    ,catalog="noveladb"
)
public class Menu  implements java.io.Serializable {


     private int codigo;
     private String url;
     private String tipo;
     private String estado;
     private Byte codigosubmenu;

    public Menu() {
    }

	
    public Menu(int codigo) {
        this.codigo = codigo;
    }
    public Menu(int codigo, String url, String tipo, String estado, Byte codigosubmenu) {
       this.codigo = codigo;
       this.url = url;
       this.tipo = tipo;
       this.estado = estado;
       this.codigosubmenu = codigosubmenu;
    }
   
     @Id 

    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="url", length=45)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="tipo", length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="codigosubmenu")
    public Byte getCodigosubmenu() {
        return this.codigosubmenu;
    }
    
    public void setCodigosubmenu(Byte codigosubmenu) {
        this.codigosubmenu = codigosubmenu;
    }




}


