package com.pallol.novela.entities;
// Generated 25/07/2019 01:09:25 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Personaje generated by hbm2java
 */
@Entity
@Table(name="personaje"
    ,catalog="noveladb"
)
public class Personaje  implements java.io.Serializable {


     private Integer personajeId;
     private Novela novela;
     private String nombre;
     private String descripcion;
     private String url;

    public Personaje() {
    }

	
    public Personaje(Novela novela) {
        this.novela = novela;
    }
    public Personaje(Novela novela, String nombre, String descripcion, String url) {
       this.novela = novela;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.url = url;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="personaje_id", unique=true, nullable=false)
    public Integer getPersonajeId() {
        return this.personajeId;
    }
    
    public void setPersonajeId(Integer personajeId) {
        this.personajeId = personajeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="novela_id_fk", nullable=false)
    public Novela getNovela() {
        return this.novela;
    }
    
    public void setNovela(Novela novela) {
        this.novela = novela;
    }

    
    @Column(name="nombre", length=75)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="url", length=65535)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


