package com.pallol.novela.entities;
// Generated 25/07/2019 01:09:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,catalog="noveladb"
)
public class Persona  implements java.io.Serializable {


     private int personaId;
     private Usuario usuario;
     private String nombre;
     private String apellido;
     private String sexo;
     private Date fechaNacimiento;
     private String url;

    public Persona() {
    }

	
    public Persona(int personaId, Usuario usuario, String nombre, Date fechaNacimiento) {
        this.personaId = personaId;
        this.usuario = usuario;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Persona(int personaId, Usuario usuario, String nombre, String apellido, String sexo, Date fechaNacimiento, String url) {
       this.personaId = personaId;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.url = url;
    }
   
     @Id 

    
    @Column(name="persona_id", unique=true, nullable=false)
    public int getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(int personaId) {
        this.personaId = personaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id_fk", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=100)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="sexo", length=20)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", nullable=false, length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="url", length=45)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


