package com.pallol.novela.entities;
// Generated 25/07/2019 01:09:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="noveladb"
)
public class Producto  implements java.io.Serializable {


     private int idproducto;
     private String nombre;
     private int precio;
     private String descripcionPequena;
     private String descripcionGrande;
     private int existencias;
     private String url;
     private Set<ProductoCompra> productoCompras = new HashSet<ProductoCompra>(0);

    public Producto() {
    }

	
    public Producto(int idproducto, int precio, int existencias) {
        this.idproducto = idproducto;
        this.precio = precio;
        this.existencias = existencias;
    }
    public Producto(int idproducto, String nombre, int precio, String descripcionPequena, String descripcionGrande, int existencias, String url, Set<ProductoCompra> productoCompras) {
       this.idproducto = idproducto;
       this.nombre = nombre;
       this.precio = precio;
       this.descripcionPequena = descripcionPequena;
       this.descripcionGrande = descripcionGrande;
       this.existencias = existencias;
       this.url = url;
       this.productoCompras = productoCompras;
    }
   
     @Id 

    
    @Column(name="idproducto", unique=true, nullable=false)
    public int getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="precio", nullable=false)
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }

    
    @Column(name="descripcion_pequena", length=45)
    public String getDescripcionPequena() {
        return this.descripcionPequena;
    }
    
    public void setDescripcionPequena(String descripcionPequena) {
        this.descripcionPequena = descripcionPequena;
    }

    
    @Column(name="descripcion_grande", length=45)
    public String getDescripcionGrande() {
        return this.descripcionGrande;
    }
    
    public void setDescripcionGrande(String descripcionGrande) {
        this.descripcionGrande = descripcionGrande;
    }

    
    @Column(name="Existencias", nullable=false)
    public int getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(int existencias) {
        this.existencias = existencias;
    }

    
    @Column(name="url", length=65535)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<ProductoCompra> getProductoCompras() {
        return this.productoCompras;
    }
    
    public void setProductoCompras(Set<ProductoCompra> productoCompras) {
        this.productoCompras = productoCompras;
    }




}


