package com.pallol.novela.entities;
// Generated 25/07/2019 01:09:25 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario",
         catalog = "noveladb"
)
public class Usuario implements java.io.Serializable {

    private int usuarioId;
    private Rol rol;
    private String codigo;
    private String contrasena;
    private boolean estado;
    private Set<Persona> personas = new HashSet<Persona>(0);
    private Set<Comentario> comentarios = new HashSet<Comentario>(0);
    private Set<UsuarioNovela> usuarioNovelas = new HashSet<UsuarioNovela>(0);
    private Set<CompraRealizada> compraRealizadas = new HashSet<CompraRealizada>(0);

    public Usuario() {
    }

    public Usuario(int usuarioId, Rol rol, String codigo, String contrasena, boolean estado) {
        this.usuarioId = usuarioId;
        this.rol = rol;
        this.codigo = codigo;
        this.contrasena = contrasena;
        this.estado = estado;
    }

    public Usuario(int usuarioId, Rol rol, String codigo, String contrasena, boolean estado, Set<Persona> personas, Set<Comentario> comentarios, Set<UsuarioNovela> usuarioNovelas, Set<CompraRealizada> compraRealizadas) {
        this.usuarioId = usuarioId;
        this.rol = rol;
        this.codigo = codigo;
        this.contrasena = contrasena;
        this.estado = estado;
        this.personas = personas;
        this.comentarios = comentarios;
        this.usuarioNovelas = usuarioNovelas;
        this.compraRealizadas = compraRealizadas;
    }

    @Id

    @Column(name = "usuario_id", unique = true, nullable = false)
    public int getUsuarioId() {
        return this.usuarioId;
    }

    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rol_id_fk", nullable = false)
    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

    @Column(name = "codigo", nullable = false, length = 75)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "contrasena", nullable = false, length = 45)
    public String getContrasena() {
        return this.contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    @Column(name = "estado", nullable = false)
    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    public Set<Persona> getPersonas() {
        return this.personas;
    }

    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    public Set<Comentario> getComentarios() {
        return this.comentarios;
    }

    public void setComentarios(Set<Comentario> comentarios) {
        this.comentarios = comentarios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    public Set<UsuarioNovela> getUsuarioNovelas() {
        return this.usuarioNovelas;
    }

    public void setUsuarioNovelas(Set<UsuarioNovela> usuarioNovelas) {
        this.usuarioNovelas = usuarioNovelas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    public Set<CompraRealizada> getCompraRealizadas() {
        return this.compraRealizadas;
    }

    public void setCompraRealizadas(Set<CompraRealizada> compraRealizadas) {
        this.compraRealizadas = compraRealizadas;
    }

}
