package com.pallol.novela.entities;
// Generated 25/07/2019 01:09:25 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioNovela generated by hbm2java
 */
@Entity
@Table(name = "usuario_novela",
         catalog = "noveladb"
)
public class UsuarioNovela implements java.io.Serializable {

    private int usuarioNovelaId;
    private Novela novela;
    private Usuario usuario;

    public UsuarioNovela() {
    }

    public UsuarioNovela(int usuarioNovelaId, Novela novela, Usuario usuario) {
        this.usuarioNovelaId = usuarioNovelaId;
        this.novela = novela;
        this.usuario = usuario;
    }

    @Id

    @Column(name = "usuario_novela_id", unique = true, nullable = false)
    public int getUsuarioNovelaId() {
        return this.usuarioNovelaId;
    }

    public void setUsuarioNovelaId(int usuarioNovelaId) {
        this.usuarioNovelaId = usuarioNovelaId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "novela_id_fk", nullable = false)
    public Novela getNovela() {
        return this.novela;
    }

    public void setNovela(Novela novela) {
        this.novela = novela;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario_id_fk", nullable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}
